from typing import Dict, List
from pathlib import Path
import uuid
from loguru import logger
from fpdf import FPDF
from PIL import Image
import os

from config import settings

class PDFService:
    """Service for creating downloadable PDF comics"""
    
    def __init__(self):
        self.pdf_output_dir = Path(settings.pdf_output_dir)
    
    async def create_comic_pdf(
        self,
        title: str,
        panels: List[Dict],
        images: Dict[int, str],
        dialogues: Dict[int, str]
    ) -> str:
        """
        Create a PDF comic from panels, images, and dialogues.
        """
        try:
            logger.info(f"Creating PDF for comic: {title}")
            
            pdf = FPDF(orientation='P', unit='mm', format='A4')
            pdf.add_page()
            
            # Add title page
            self._add_title_page(pdf, title)
            
            # Add comic panels
            for i in range(1, len(panels) + 1):
                pdf.add_page()
                self._add_comic_panel(
                    pdf=pdf,
                    panel_num=i,
                    panel_data=panels[i - 1],
                    image_path=images.get(i, ""),
                    dialogue=dialogues.get(i, "")
                )
            
            # Save PDF
            pdf_id = str(uuid.uuid4())
            pdf_filename = f"comic_{pdf_id}.pdf"
            pdf_path = self.pdf_output_dir / pdf_filename
            
            pdf.output(str(pdf_path))
            logger.success(f"PDF created successfully: {pdf_path}")
            
            return f"/outputs/pdfs/{pdf_filename}"
            
        except Exception as e:
            logger.error(f"Error creating PDF: {str(e)}")
            raise
    
    def _add_title_page(self, pdf: FPDF, title: str) -> None:
        """
        Add a title page to the PDF.
        """
        pdf.set_font("Arial", "B", 28)
        pdf.ln(50)
        pdf.multi_cell(0, 10, title, align="C")
        
        pdf.set_font("Arial", "", 12)
        pdf.ln(20)
        pdf.multi_cell(0, 10, "Generated by ComicCraft AI", align="C")
    
    def _add_comic_panel(
        self,
        pdf: FPDF,
        panel_num: int,
        panel_data: Dict,
        image_path: str,
        dialogue: str
    ) -> None:
        """
        Add a comic panel to the PDF.
        """
        try:
            # Add panel number and description
            pdf.set_font("Arial", "B", 14)
            pdf.cell(0, 10, f"Panel {panel_num}", ln=True)
            
            # Add panel description
            pdf.set_font("Arial", "", 10)
            pdf.multi_cell(0, 5, panel_data.get('description', ''))
            pdf.ln(5)
            
            # Add image if available
            if image_path and os.path.exists(image_path):
                try:
                    pdf.image(image_path, x=10, w=190, h=100)
                except Exception as e:
                    logger.warning(f"Could not add image: {str(e)}")
            else:
                # Add placeholder
                pdf.set_font("Arial", "I", 10)
                pdf.cell(0, 10, "[Image Placeholder]", border=1, ln=True)
            
            pdf.ln(5)
            
            # Add dialogue
            if dialogue:
                pdf.set_font("Arial", "", 11)
                pdf.set_text_color(0, 0, 100)
                pdf.multi_cell(0, 5, f'"${dialogue}"')
            
            pdf.set_text_color(0, 0, 0)
            
        except Exception as e:
            logger.error(f"Error adding panel to PDF: {str(e)}")
    
    async def merge_pdfs(
        self,
        pdf_paths: List[str],
        output_filename: str = None
    ) -> str:
        """
        Merge multiple PDFs into one.
        """
        try:
            from PyPDF2 import PdfMerger
            
            merger = PdfMerger()
            
            for pdf_path in pdf_paths:
                if os.path.exists(pdf_path):
                    merger.append(pdf_path)
            
            output_filename = output_filename or f"comic_merged_{str(uuid.uuid4())}.pdf"
            output_path = self.pdf_output_dir / output_filename
            
            merger.write(str(output_path))
            merger.close()
            
            logger.info(f"PDFs merged successfully: {output_path}")
            return f"/outputs/pdfs/{output_filename}"
            
        except Exception as e:
            logger.error(f"Error merging PDFs: {str(e)}")
            raise
